[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fts"
version = "0.5.0"
description = "Peer to peer file and directory tranfer system"
authors = [
  { name = "Terabase Studios", email = "terabasestudios@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "aiofiles==24.1.0",
    "argcomplete==3.6.2",
    "cryptography==45.0.7",
    "psutil==7.0.0",
    "tqdm==4.67.1",
    "prompt_toolkit==3.0.52",
    "gooey==1.0.8.1",
]



[project.scripts]
fts = "fts.__init__:main"